### ISSUE TITLE
Photo Nuclear DQM not working with upKaons branch

### ISSUE THREAD

**Issue by LisaALoman** [LDMXAnalysis/ldmx-sw#1069] opened 2022-06-07 13:32 UTC
I am trying to run Photo Nuclear DQM when I am doing simulations using the `upKaons` branch and a beam energy of 8GeV. I got some help to look into it and it seems like the daughter track IDs are not in the particle map.
I am getting the following error:
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
/etc/entry.sh: line 60:    81 Aborted                 (core dumped) fire config.py
```
In my config file I am using the simulator function `ecal.kaon_pn`, which is in a modified version of `Biasing/python/ecal.py` .

This is the configuration file:

```
from LDMX.Framework import ldmxcfg

p=ldmxcfg.Process("test")
p.run = 1

from LDMX.SimCore import bias_operators
from LDMX.SimCore import simulator
from LDMX.Ecal import EcalGeometry
from LDMX.Hcal import HcalGeometry
import LDMX.Ecal.ecal_hardcoded_conditions as ecal_conditions
import LDMX.Hcal.hcal_hardcoded_conditions as hcal_conditions

from LDMX.Biasing import ecal  #target
from LDMX.SimCore import generators
mysim = ecal.kaon_pn('ldmx-det-v13', generators.single_8gev_e_upstream_tagger()) #changed 4 to 8
mysim.description = "ECal Kaon Test Simulation, 8GeV"
print(mysim)

# NEW to fix everything; 3.0.0 broke imports yet again...
import LDMX.Ecal.digi as ecal_digi
import LDMX.Hcal.digi as hcal_digi
import LDMX.Ecal.vetos as ecal_vetos
import LDMX.Hcal.hcal as hcal_py
from LDMX.Recon.simpleTrigger import simpleTrigger
from LDMX.Recon.electronCounter import ElectronCounter #to allow for multi-e, electron counter needed


from LDMX.TrigScint.trigScint import TrigScintDigiProducer
from LDMX.TrigScint.trigScint import TrigScintClusterProducer
from LDMX.TrigScint.trigScint import trigScintTrack

tsDigisUp   = TrigScintDigiProducer.up()
tsDigisTag  = TrigScintDigiProducer.tagger()
tsDigisDown = TrigScintDigiProducer.down()

#these lines required for trigger skimming
eCount = ElectronCounter(1, "ElectronCounter") #first argument is number of electrons in simulation
eCount.use_simulated_electron_number = True
simpleTrigger.end_layer = 20
simpleTrigger.start_layer = 0 #default is 1, force to include first layer
#these two lines turn on trigger skimming
#p.skimDefaultIsDrop()
#p.skimConsider(simpleTrigger.instanceName)

p.sequence=[ mysim,
        ecal_digi.EcalDigiProducer(),
        ecal_digi.EcalRecProducer(),
        ecal_vetos.EcalVetoProcessor(),
        hcal_digi.HcalDigiProducer(),
        hcal_digi.HcalRecProducer(),
        hcal_py.HcalVetoProcessor(),
        tsDigisUp, tsDigisTag, tsDigisDown,
        #trigScintTrack,
        eCount,
        simpleTrigger
        ]

p.outputFiles=["upKaons8_testprod.root"]

p.maxTriesPerEvent = 1 #max number of attempts to create an event before moving on, default is 1
p.maxEvents = 100000

p.logFrequency = 100

 #generate dqm plots for valivation of the physics

 #note!: The code seems to work without this part

from LDMX.DQM import dqm                   
p.sequence.append( dqm.PhotoNuclearDQM() )
p.histogramFile = "testHistFile.root"


#print(p)


```
This is the modified version of Biasing/python/ecal.py:

```
"""Example configurations for producing biased interactions in the ECal. 

    Example
    -------
        
        from LDMX.Biasing import ecal
"""

from LDMX.SimCore import simulator
from LDMX.SimCore import generators
from LDMX.SimCore import bias_operators
from LDMX.Biasing import filters
from LDMX.Biasing import util
from LDMX.Biasing import include as includeBiasing
from LDMX.Biasing import particle_filter

def photo_nuclear( detector, generator ) :
    """Example configuration for producing photo-nuclear reactions in the ECal.  
       
    In this particular example, 4 GeV electrons are fired upstream of the 
    tagger tracker.  The TargetBremFilter filters out all events that don't 
    produced a brem in the target with an energy greater than 2.5 GeV.  The
    brems are allowed to propagate to the ECal at which point they are 
    checked by the EcalProcessFilter.  Only events that see the brem photon
    undergo a photo-nucler reaction in the ECal are kept. 

    Parameters
    ----------

    detector : str
        Path to the detector 
    generator : PrimaryGenerator
        generator to use

    Returns
    -------
    Instance of the simulator configured for ECal photo-nuclear.

    Example
    -------

        ecal_pn_sim = ecal.photo_nuclear('ldmx-det-v12')

    """


    # Instantiate the simulator. 
    sim = simulator.simulator("photo-nuclear")
    
    # Set the path to the detector to use.
    #   the second parameter says we want to include scoring planes
    sim.setDetector( detector , True )
    
    # Set run parameters
    sim.runNumber = 0
    sim.description = "ECal photo-nuclear, xsec bias 450"
    sim.beamSpotSmear = [20., 80., 0.] #mm
    
    sim.generators.append( generator )
    
    # Enable and configure the biasing
    #   In order to conform to older samples,
    #   we can only attach to some of the volumes in the ecal
    #   so we ask for this operator to be attached to the 'old_ecal'
    #  biasing factors are 450., 2500. for 4GeV, 550., 4500. for 8GeV
    sim.biasing_operators = [ bias_operators.PhotoNuclear('old_ecal',550.,4500.,only_children_of_primary = True) ] 

    # the following filters are in a library that needs to be included
    includeBiasing.library()

    # Configure the sequence in which user actions should be called.
    sim.actions.extend([
            filters.TaggerVetoFilter(),
            # Only consider events where a hard brem occurs
            filters.TargetBremFilter(),
            # Only consider events where a PN reaction happnes in the ECal
            filters.EcalProcessFilter(),     
            # Tag all photo-nuclear tracks to persist them to the event.
            util.TrackProcessFilter.photo_nuclear()
    ])

    return sim


def kaon_pn( detector, generator ) :
    """Adding kaon filtering to the above photo_nuclear generator

    Parameters
    ----------

    detector : str
        Path to the detector 
    generator : PrimaryGenerator
        generator to use

    """


    # Instantiate the simulator. 
    sim = simulator.simulator("kaon-pn")
    
    # Set the path to the detector to use.
    #   the second parameter says we want to include scoring planes
    sim.setDetector( detector , True )
    
    # Set run parameters
    sim.runNumber = 0
    sim.description = "ECal photo-nuclear,kaon filtering,  xsec bias 450"
    sim.beamSpotSmear = [20., 80., 0.] #mm
    
    sim.generators.append( generator )
    
    # Enable and configure the biasing
    #   In order to conform to older samples,
    #   we can only attach to some of the volumes in the ecal
    #   so we ask for this operator to be attached to the 'old_ecal'
    #  biasing factors are 450., 2500. for 4GeV, 550., 4500. for 8GeV
    sim.biasing_operators = [ bias_operators.PhotoNuclear('old_ecal',550.,4500.,only_children_of_primary = True) ]

    # the following filters are in a library that needs to be included
    includeBiasing.library()

    # Configure the sequence in which user actions should be called.
    sim.actions.extend([
            filters.TaggerVetoFilter(),
            # Only consider events where a hard brem occurs
            filters.TargetBremFilter(),
            # Only consider events where a PN reaction happnes in the ECal
            filters.EcalProcessFilter(),
            #Filter for events with a kaon daughter
            particle_filter.PhotoNuclearProductsFilter.kaon(),
            # Tag all photo-nuclear tracks to persist them to the event.
            util.TrackProcessFilter.photo_nuclear()
    ])

    return sim



```

Anyone got any ideas on what is going wrong here? 
 @tomeichlersmith

**Comment by tomeichlersmith** [comment] 2022-06-07 15:41
The error implies that we are attempting to call an "unchecked" `map::at` with an input that does not exist. (By "unchecked", I mean we don't check that the key we are requesting exists in the map.) This generates the `std::out_of_range` exception which is not caught by anyone causing the program halt. The `std::map` object that the DQM uses is the map of sim particles from the event, so I think that is the first place to check.

## Unchecked `at` used in PhotoNuclearDQM

**Getting recoil electron**

https://github.com/LDMX-Software/ldmx-sw/blob/c6ab11c77a7989d1d9cab4cb7eb3e8691c94d612/DQM/src/DQM/PhotoNuclearDQM.cxx#L111

which calls

https://github.com/LDMX-Software/ldmx-sw/blob/c6ab11c77a7989d1d9cab4cb7eb3e8691c94d612/Tools/src/Tools/AnalysisUtils.cxx#L32

This code assumes that the particle with track ID 1 was saved into the particle map. This assumption _should_ be safe since track ID 1 is primary particles and they _should_ all be saved.

**Getting PN Gamma**

https://github.com/LDMX-Software/ldmx-sw/blob/c6ab11c77a7989d1d9cab4cb7eb3e8691c94d612/DQM/src/DQM/PhotoNuclearDQM.cxx#L121

which calls

https://github.com/LDMX-Software/ldmx-sw/blob/c6ab11c77a7989d1d9cab4cb7eb3e8691c94d612/Tools/src/Tools/AnalysisUtils.cxx#L43-L57

This code assumes that _all of the child/daughter particles of the recoil electron are in the particle map_. I think this assumption works when the electron track is stopped in the target, but if direct children of the recoil electron are produced in the calorimeters, then they would not be saved. More investigation to follow...

**Comment by tomeichlersmith** [comment] 2022-06-07 18:22
I was able to reproduce the error so I have a good place to start from.

Putting in printouts around the map::at calls highlighted above showed that the lower one on line 54 of AnalysisUtils is what is throwing the exception.

```
Getting SimParticles...got 21
Getting recoil electron...got 1
Getting PN Gamma...Getting particle 5 done
Getting gd 7terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
/home/ldmx.sh: line 60: 12542 Aborted                 (core dumped) fire config.py
```
This function is attempting to deduce which particle is "the" PN gamma. It follows the criteria
1. Child of the recoil electron
2. Children produced by PN
3. Above input threshold

The code for criteria (2) is broken because it needs to check the children of the child particle, but sometimes those "grand children" aren't saved into the output particle map. This can be resolved pretty directly by adding a criteria making sure the grand children exist. Going to push these patches now...

**Comment by omar-moreno** [comment] 2022-06-07 18:34
For typical samples, the PN gamma should always come from the recoil electron and should crash if it doesn't.  The fact that it's crashing here is pointing to an issue with the samples and not the code.

**Comment by omar-moreno** [comment] 2022-06-07 18:35
Maybe, add an exception is the PN gamma is not associated with the recoil instead.

**Comment by EinarElen** [comment] 2023-03-05 16:13
With a quick and dirty fix to the TaggerVetoFilter inefficiency, I am _still_ seeing crashes with the PN DQM. This happens for an event where the PN gamma is associated with the recoil electron and all the PN daughters are present in the particle map. 

The issue is what Tom listed above, but it is also relevant for granddaughter particles to non-PN daughters. In my case, the following photon 
``` 
Particle with id: 13
SimParticle { energy: 0.76751, PDG ID: 22, genStatus: 0, time: 0.00440825, vertex: ( -4.40388, -30.8082, 0.103201 ), endPoint: ( 37.0469, -49.5836, 321.966 ), momentum: ( 0.00259368, 0.00288273, 0.7675 ), endPointMomentum: ( 0, -0, 0 ), mass: 0, nDaughters: 2, nParents: 1, processType: 5, vertex volume: target }
Has parents: 1
And daughters:  16 15
```
happened to checked before the PN gamma in the particle map
``` 
Particle with id: 12
SimParticle { energy: 3310.45, PDG ID: 22, genStatus: 0, time: 0.00426283, vertex: ( -4.40405, -30.8083, 0.0596054 ), endPoint: ( -3.83989, -30.875, 292.675 ), momentum: ( 6.38247, -0.754167, 3310.44 ), endPointMomentum: ( 0, -0, 0 ), mass: 0, nDaughters: 18, nParents: 1, processType: 5, vertex volume: target }
Has parents: 1
And daughters:  33 30 28 34 23 21 20 18 32 31 29 27 26 25 24 22 19 17
```

Since particle 16 isn't in the map, this crashes despite the PN products being present. This can be fixed by just checking that the granddaughter particle is in the map before accessing it, as Tom suggested above. The reason Tom's fix didn't work before was the issue with the tagger filter.

**Comment by EinarElen** [comment] 2023-04-21 18:35
So... this sadly still isn't fixed. With the config relatively minimal config below

```python
#!/bin/python
from LDMX.Framework import ldmxcfg

det = 14
run = 1
beamEnergy=4 #in GeV
maxEvents = 100
thisPassName = "sim"
detector=f'ldmx-det-v{det}'
p = ldmxcfg.Process(thisPassName)

p.maxEvents = maxEvents
from LDMX.Biasing import ecal, particle_filter
from LDMX.DQM import dqm
from LDMX.SimCore import generators as gen
import LDMX.Ecal.EcalGeometry
import LDMX.Ecal.ecal_hardcoded_conditions
import LDMX.Hcal.HcalGeometry
import LDMX.Hcal.hcal_hardcoded_conditions
from LDMX.SimCore import simulator
from LDMX.Biasing import filters
from LDMX.Biasing import util
from LDMX.Biasing import include as includeBiasing


sim = ecal.photo_nuclear(detector, gen.single_4gev_e_upstream_tagger())
p.run = run

p.outputFiles = ['PNtest.root']
p.histogramFile = 'PNtesthist.root'
p.logFrequency = 1
p.termLogLevel = 2
p.sequence = [sim, dqm.PhotoNuclearDQM()]
```

You will still get an out of range error from the particle map lookup

```shell
[ EcalProcessFilter ]: 16 Brem photon produced 36 particle via biasWrapper(photonNuclear) process.
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
```

I've been trying to find out what the issue is and I really can't find what the exact issue is. However, I took an attempt at just rewriting the relevant code  instead and that seems to have solved the problem somehow. Instead of the existing 

```C++ 
const ldmx::SimParticle* getPNGamma(
    const std::map<int, ldmx::SimParticle>& particleMap,
    const ldmx::SimParticle* recoil, const float& energyThreshold) {
  // Get all of the daughter track IDs
  auto daughterTrackIDs{recoil->getDaughters()};

  auto pit = std::find_if(
      daughterTrackIDs.begin(), daughterTrackIDs.end(),
      [energyThreshold, particleMap](const int& id) {
        // Get the SimParticle from the map
        auto daughter{particleMap.at(id)};

        // If the particle doesn't have any daughters, return false
        if (daughter.getDaughters().size() == 0
            or 
            particleMap.find(daughter.getDaughters().front()) != particleMap.end()
           ) return false;

        // If the particle has daughters that were a result of a
        // photo-nuclear reaction, and its energy is above threshold,
        // then tag it as the PN gamma.
        return (
            (particleMap.at(daughter.getDaughters().front()).getProcessType() ==
             ldmx::SimParticle::ProcessType::photonNuclear) &&
            (daughter.getEnergy() >= energyThreshold));
      });

  // If a PN daughter was found, return it.
  if (pit != daughterTrackIDs.end()) return &particleMap.at(*pit);

  return nullptr;
}
``` 

I went ahead and trying to write something along these lines
```C++ 
// Search the recoil electrons daughters for a photon
// Check if the photon has daughters and if so, if they were produced by PN
//

bool doesParticleHavePNDaughters(
    const ldmx::SimParticle& gamma,
    const std::map<int, ldmx::SimParticle>& particleMap) {
  // TODO is there a point in continueing to loop after the first ID in the map
  // has been found?
  for (auto daughterID : gamma.getDaughters()) {
    if (particleMap.find(daughterID) != std::end(particleMap)) {
      const auto daughter{particleMap.at(daughterID)};
      const auto processType{daughter.getProcessType()};
      if (processType == ldmx::SimParticle::ProcessType::photonNuclear) {
        return true;
      }  // Was it PN?
    }    // Was it in the map?
  }      // Loop over daughter particles
  return false;
}

const ldmx::SimParticle* getPNGamma(
    const std::map<int, ldmx::SimParticle>& particleMap,
    const ldmx::SimParticle* recoil, const float& energyThreshold) {
  auto recoilDaughters{recoil->getDaughters()};
  for (auto recoilDaughterID : recoilDaughters) {
    // Have we stored the recoil daughter?
    if (particleMap.find(recoilDaughterID) != std::end(particleMap)) {
      auto recoilDaughter{particleMap.at(recoilDaughterID)};
      // Is it a gamma?
      if (recoilDaughter.getPdgID() == 22) {
        // Does it have enough energy?
        if (recoilDaughter.getEnergy() >= energyThreshold) {
          // Are its daughters PN products?
          if (doesParticleHavePNDaughters(recoilDaughter, particleMap)) {
            return &particleMap.at(recoilDaughterID);
          }
        }
      }
    }
  }
  return nullptr;
}
```

Maybe its a bit verbose, but it does seem to work

**Comment by EinarElen** [comment] 2023-04-23 14:44
Just adding here that this issue shows up both with v14 and v12. I think the reason for this not showing up in the ecal PN validation configuration is that it is adding `dqm.all_dqm` which does not include the photonuclear DQM.

**Closed as completed** 2023-04-24 16:15 UTC
