### ISSUE TITLE
Linker warnings during build

### ISSUE THREAD

**Issue by JeremyMcCormick** [LDMXAnalysis/ldmx-sw#365] opened 2017-08-14 20:28 UTC
```
[ 94%] Linking CXX executable ldmx-sim
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libGLU.so when searching for -lGLU
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libGL.so when searching for -lGL
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libX11.so when searching for -lX11
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libXext.so when searching for -lXext
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libm.so when searching for -lm
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libpthread.so when searching for -lpthread
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libc.so when searching for -lc
```

Seems to be an issue with the Anaconda toolchain and 32-bit system libraries from the default location (/usr/lib instead of /lib64).

**Comment by omar-moreno** [comment] 2017-10-30 07:10
Can't reproduce this issue so I'm closing it.

**Closed by omar-moreno** 2017-10-30 07:10 UTC
Labels: bug
